version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/var/www/nextjs-strapi-app/client
    restart: always
    env_file: ./client/.env.dev
    networks:
      - strapi_local

  nginx:
    depends_on:
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - strapi_local

  strapi:
    container_name: strapi
    build:
      context: ./strapi
      dockerfile: Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./strapi/config:/var/www/nextjs-strapi-app/stripe/config
      - ./strapi/src:/var/www/nextjs-strapi-app/stripe/src
      - ./strapi/package.json:/var/www/nextjs-strapi-app/stripe/package.json
      - ./strapi/yarn.lock:/var/www/nextjs-strapi-app/stripe/yarn.lock
      - ./strapi/.env:/var/www/nextjs-strapi-app/stripe/.env
      - ./strapi/public/uploads:/var/www/nextjs-strapi-app/stripe/public/uploads
    # volumes:
    #   - ./strapi/config:/opt/app/config
    #   - ./strapi/src:/opt/app/src
    #   - ./strapi/package.json:/opt/package.json
    #   - ./strapi/yarn.lock:/opt/yarn.lock
    #   - ./strapi/.env:/opt/app/.env
    #   - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi_local
    depends_on:
      - strapiDB_local

  strapiDB_local:
    container_name: strapiDB_local
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: always
    env_file: .env
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strapidb
    # environment:
    #   POSTGRES_USER: ${DATABASE_USERNAME}
    #   POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #   POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data_local:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - strapi_local

volumes:
  strapi-data_local:

networks:
  strapi_local:
    name: Strapi
    driver: bridge